// <auto-generated />
using System;
using CrediAvanzaAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrediAvanzaAPI.Migrations
{
    [DbContext(typeof(DbNegocioContext))]
    [Migration("20260713232410_SincronizarModelo")]
    partial class SincronizarModelo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrediAvanzaAPI.Models.Agencia", b =>
                {
                    b.Property<int>("NCodAge")
                        .HasColumnType("int")
                        .HasColumnName("nCodAge");

                    b.Property<string>("CCorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cCorreoELectronico");

                    b.Property<string>("CDirecAge")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("cDirecAge");

                    b.Property<string>("CNomAge")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cNomAge");

                    b.Property<string>("CTelefAge")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cTelefAge");

                    b.HasKey("NCodAge")
                        .HasName("PK__Agencias__771BAD3EF24D8FB8");

                    b.ToTable("Agencias");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CapacidadPago", b =>
                {
                    b.Property<int>("IdCapacidadPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCapacidadPago"));

                    b.Property<decimal>("DGastosAlimentacion")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("dGastosAlimentacion");

                    b.Property<decimal>("DGastosEducacion")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("dGastosEducacion");

                    b.Property<decimal>("DGastosSalud")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("dGastosSalud");

                    b.Property<decimal>("DOtrosGastos")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("dOtrosGastos");

                    b.Property<decimal>("DOtrosIngresos")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("dOtrosIngresos");

                    b.HasKey("IdCapacidadPago");

                    b.ToTable("CapacidadPago", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CatSegmentoUsura", b =>
                {
                    b.Property<int>("NCodSegmento")
                        .HasColumnType("int")
                        .HasColumnName("nCodSegmento");

                    b.Property<bool>("BEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("bEstado");

                    b.Property<string>("CDescripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cDescripcion");

                    b.Property<decimal?>("NMultSmmax")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("nMultSMMax");

                    b.Property<decimal>("NMultSmmin")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("nMultSMMin");

                    b.HasKey("NCodSegmento")
                        .HasName("PK__CatSegme__70B6321C501B9212");

                    b.ToTable("CatSegmentoUsura", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CatalogoCodigo", b =>
                {
                    b.Property<int>("NCodigo")
                        .HasColumnType("int")
                        .HasColumnName("nCodigo");

                    b.Property<int>("NValor")
                        .HasColumnType("int")
                        .HasColumnName("nValor");

                    b.Property<string>("CNomCod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cNomCod");

                    b.Property<int?>("NEstados")
                        .HasColumnType("int")
                        .HasColumnName("nEstados");

                    b.Property<int?>("NTipoCodigo")
                        .HasColumnType("int")
                        .HasColumnName("nTipoCodigo");

                    b.HasKey("NCodigo", "NValor");

                    b.ToTable("CatalogoCodigos");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<string>("CProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cProducto");

                    b.Property<int>("IdNegocio")
                        .HasColumnType("int");

                    b.Property<decimal>("NCantidadCompra")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("nCantidadCompra");

                    b.Property<decimal>("NPrecioTotal")
                        .HasColumnType("money")
                        .HasColumnName("nPrecioTotal");

                    b.Property<decimal>("NPrecioXunidad")
                        .HasColumnType("money")
                        .HasColumnName("nPrecioXUnidad");

                    b.Property<int>("NUnidadMedida")
                        .HasColumnType("int")
                        .HasColumnName("nUnidadMedida");

                    b.HasKey("IdCompra")
                        .HasName("PK_CompraDetalle");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Conyuge", b =>
                {
                    b.Property<int>("IdConyuge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConyuge"));

                    b.Property<string>("CCelular")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cCelular");

                    b.Property<string>("CDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cDocumento");

                    b.Property<string>("CNombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cNombres");

                    b.Property<string>("CPrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cPrimerApellido");

                    b.Property<string>("CSegundoApellido")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cSegundoApellido");

                    b.Property<string>("CTelefono")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cTelefono");

                    b.Property<int>("NTipoDocumento")
                        .HasColumnType("int")
                        .HasColumnName("nTipoDocumento");

                    b.HasKey("IdConyuge");

                    b.ToTable("Conyuge", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CredCalenGasto", b =>
                {
                    b.Property<int>("IdCalenGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCalenGasto"));

                    b.Property<DateTime>("DFecAsig")
                        .HasColumnType("datetime")
                        .HasColumnName("dFecAsig");

                    b.Property<int?>("NCodAgePersAsig")
                        .HasColumnType("int")
                        .HasColumnName("nCodAgePersAsig");

                    b.Property<int>("NCodGasto")
                        .HasColumnType("int")
                        .HasColumnName("nCodGasto");

                    b.Property<decimal>("NMonto")
                        .HasColumnType("money")
                        .HasColumnName("nMonto");

                    b.Property<decimal?>("NMontoIgv")
                        .HasColumnType("money")
                        .HasColumnName("nMontoIGV");

                    b.Property<decimal?>("NMontoIgvpag")
                        .HasColumnType("money")
                        .HasColumnName("nMontoIGVPag");

                    b.Property<decimal>("NMontoPag")
                        .HasColumnType("money")
                        .HasColumnName("nMontoPag");

                    b.Property<decimal?>("NMontoSinIgv")
                        .HasColumnType("money")
                        .HasColumnName("nMontoSinIGV");

                    b.Property<decimal?>("NMontoSinIgvpag")
                        .HasColumnType("money")
                        .HasColumnName("nMontoSinIGVPag");

                    b.Property<int>("NNroCalen")
                        .HasColumnType("int")
                        .HasColumnName("nNroCalen");

                    b.Property<int>("NNroCuota")
                        .HasColumnType("int")
                        .HasColumnName("nNroCuota");

                    b.HasKey("IdCalenGasto");

                    b.ToTable("CredCalenGastos");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CredCalendCond", b =>
                {
                    b.Property<int>("IdCredCalendCond")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCredCalendCond"));

                    b.Property<bool?>("BCobroDom")
                        .HasColumnType("bit")
                        .HasColumnName("bCobroDom");

                    b.Property<bool?>("BCobroFer")
                        .HasColumnType("bit")
                        .HasColumnName("bCobroFer");

                    b.Property<bool?>("BCobroSab")
                        .HasColumnType("bit")
                        .HasColumnName("bCobroSab");

                    b.Property<bool?>("BCuotaDoble")
                        .HasColumnType("bit")
                        .HasColumnName("bCuotaDoble");

                    b.Property<int?>("IdCalenGasto")
                        .HasColumnType("int");

                    b.Property<int>("NCuotas")
                        .HasColumnType("int")
                        .HasColumnName("nCuotas");

                    b.Property<int?>("NDiaFijo")
                        .HasColumnType("int")
                        .HasColumnName("nDiaFijo");

                    b.Property<int>("NNroCalen")
                        .HasColumnType("int")
                        .HasColumnName("nNroCalen");

                    b.Property<int>("NPlazo")
                        .HasColumnType("int")
                        .HasColumnName("nPlazo");

                    b.HasKey("IdCredCalendCond");

                    b.ToTable("CredCalendCond", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CredCalendario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DFecPago")
                        .HasColumnType("datetime")
                        .HasColumnName("dFecPago");

                    b.Property<DateTime>("DFecVenc")
                        .HasColumnType("datetime")
                        .HasColumnName("dFecVenc");

                    b.Property<decimal>("NCapPag")
                        .HasColumnType("money")
                        .HasColumnName("nCapPag");

                    b.Property<decimal>("NCapital")
                        .HasColumnType("money")
                        .HasColumnName("nCapital");

                    b.Property<int?>("NCodAge")
                        .HasColumnType("int")
                        .HasColumnName("nCodAge");

                    b.Property<int?>("NCodCred")
                        .HasColumnType("int")
                        .HasColumnName("nCodCred");

                    b.Property<int>("NEstado")
                        .HasColumnType("int")
                        .HasColumnName("nEstado");

                    b.Property<decimal>("NIgv")
                        .HasColumnType("money")
                        .HasColumnName("nIgv");

                    b.Property<decimal>("NIgvPag")
                        .HasColumnType("money")
                        .HasColumnName("nIgvPag");

                    b.Property<decimal>("NIntComp")
                        .HasColumnType("money")
                        .HasColumnName("nIntComp");

                    b.Property<decimal>("NIntMor")
                        .HasColumnType("money")
                        .HasColumnName("nIntMor");

                    b.Property<decimal>("NIntMorPag")
                        .HasColumnType("money")
                        .HasColumnName("nIntMorPag");

                    b.Property<decimal>("NIntPag")
                        .HasColumnType("money")
                        .HasColumnName("nIntPag");

                    b.Property<int>("NNroCalen")
                        .HasColumnType("int")
                        .HasColumnName("nNroCalen");

                    b.Property<int>("NNroCuota")
                        .HasColumnType("int")
                        .HasColumnName("nNroCuota");

                    b.Property<decimal?>("NTotalCuota")
                        .HasColumnType("money")
                        .HasColumnName("nTotalCuota");

                    b.Property<decimal>("Ngasto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("NGasto");

                    b.HasKey("Id");

                    b.ToTable("CredCalendario", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CredCambioGasto", b =>
                {
                    b.Property<int>("NIdCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nIdCambio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NIdCambio"));

                    b.Property<DateOnly>("DFechaCambio")
                        .HasColumnType("date")
                        .HasColumnName("dFechaCambio");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("NCodCred")
                        .HasColumnType("int")
                        .HasColumnName("nCodCred");

                    b.Property<decimal>("NMontoNuevo")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("nMontoNuevo");

                    b.Property<decimal>("NMontoOriginal")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("nMontoOriginal");

                    b.HasKey("NIdCambio");

                    b.ToTable("CredCambioGasto", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CredFeriado", b =>
                {
                    b.Property<int>("NIdFeriado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nIdFeriado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NIdFeriado"));

                    b.Property<bool>("BEstado")
                        .HasColumnType("bit")
                        .HasColumnName("bEstado");

                    b.Property<string>("CDescripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("cDescripcion");

                    b.Property<DateTime>("DFecha")
                        .HasColumnType("datetime")
                        .HasColumnName("dFecha");

                    b.HasKey("NIdFeriado");

                    b.ToTable("CredFeriado", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CredFeriadoAge", b =>
                {
                    b.Property<int>("IdCredFeriadoAge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCredFeriadoAge"));

                    b.Property<DateTime>("DFecha")
                        .HasColumnType("datetime")
                        .HasColumnName("dFecha");

                    b.Property<int>("NCodAge")
                        .HasColumnType("int")
                        .HasColumnName("nCodAge");

                    b.Property<int>("NIdFeriado")
                        .HasColumnType("int")
                        .HasColumnName("nIdFeriado");

                    b.HasKey("IdCredFeriadoAge");

                    b.ToTable("CredFeriadoAge", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CredGasto", b =>
                {
                    b.Property<int>("IdGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGasto"));

                    b.Property<string>("CDescripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cDescripcion");

                    b.Property<int>("NPeriodo")
                        .HasColumnType("int")
                        .HasColumnName("nPeriodo");

                    b.Property<int>("NProd")
                        .HasColumnType("int")
                        .HasColumnName("nProd");

                    b.Property<decimal>("NRangoFinal")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("nRangoFinal");

                    b.Property<decimal>("NRangoInicial")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("nRangoInicial");

                    b.Property<int>("NSubProd")
                        .HasColumnType("int")
                        .HasColumnName("nSubProd");

                    b.Property<int>("NTipoCargo")
                        .HasColumnType("int")
                        .HasColumnName("nTipoCargo");

                    b.Property<int>("NTipoGasto")
                        .HasColumnType("int")
                        .HasColumnName("nTipoGasto");

                    b.Property<decimal>("NValor")
                        .HasColumnType("money")
                        .HasColumnName("nValor");

                    b.HasKey("IdGasto");

                    b.ToTable("CredGastos");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CredLineaCredito", b =>
                {
                    b.Property<int>("NCodLinea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nCodLinea");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NCodLinea"));

                    b.Property<bool>("BAplicaSegmentacionUsura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("bAplicaSegmentacionUsura");

                    b.Property<bool>("BEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("bEstado");

                    b.Property<string>("CDescripcion")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("cDescripcion");

                    b.Property<string>("CLinea")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("cLinea");

                    b.Property<decimal>("NMontoMax")
                        .HasColumnType("money")
                        .HasColumnName("nMontoMax");

                    b.Property<decimal>("NMontoMin")
                        .HasColumnType("money")
                        .HasColumnName("nMontoMin");

                    b.Property<int>("NPlazoMax")
                        .HasColumnType("int")
                        .HasColumnName("nPlazoMax");

                    b.Property<int>("NPlazoMin")
                        .HasColumnType("int")
                        .HasColumnName("nPlazoMin");

                    b.Property<int>("NProd")
                        .HasColumnType("int")
                        .HasColumnName("nProd");

                    b.Property<int>("NSubProd")
                        .HasColumnType("int")
                        .HasColumnName("nSubProd");

                    b.Property<decimal>("NTasaCom")
                        .HasColumnType("money")
                        .HasColumnName("nTasaCom");

                    b.Property<int?>("Periodicidad")
                        .HasColumnType("int");

                    b.HasKey("NCodLinea")
                        .HasName("PK__CredLine__50A988C3CC0EBAA0");

                    b.ToTable("CredLineaCredito", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Credito", b =>
                {
                    b.Property<int>("NCodCred")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nCodCred");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NCodCred"));

                    b.Property<DateTime>("DFecVig")
                        .HasColumnType("datetime")
                        .HasColumnName("dFecVig");

                    b.Property<int?>("IdCapacidadPago")
                        .HasColumnType("int");

                    b.Property<int?>("IdConyuge")
                        .HasColumnType("int");

                    b.Property<int?>("IdCredCalendCond")
                        .HasColumnType("int");

                    b.Property<int?>("IdDocumentacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdFiador")
                        .HasColumnType("int");

                    b.Property<int?>("IdGarantia")
                        .HasColumnType("int");

                    b.Property<int?>("IdNegocio")
                        .HasColumnType("int");

                    b.Property<int?>("IdPersona")
                        .HasColumnType("int");

                    b.Property<int?>("NAceptaTerminos")
                        .HasColumnType("int")
                        .HasColumnName("nAceptaTerminos");

                    b.Property<int?>("NCobroEnAgencia")
                        .HasColumnType("int")
                        .HasColumnName("nCobroEnAgencia");

                    b.Property<int>("NCodAge")
                        .HasColumnType("int")
                        .HasColumnName("nCodAge");

                    b.Property<int?>("NCodLinea")
                        .HasColumnType("int")
                        .HasColumnName("nCodLinea");

                    b.Property<int?>("NDiasAtraso")
                        .HasColumnType("int")
                        .HasColumnName("nDiasAtraso");

                    b.Property<int>("NEstado")
                        .HasColumnType("int")
                        .HasColumnName("nEstado");

                    b.Property<decimal?>("NMontoCuota")
                        .HasColumnType("money")
                        .HasColumnName("nMontoCuota");

                    b.Property<decimal?>("NMora")
                        .HasColumnType("money")
                        .HasColumnName("nMora");

                    b.Property<int>("NNroCuotas")
                        .HasColumnType("int")
                        .HasColumnName("nNroCuotas");

                    b.Property<int>("NPeriodo")
                        .HasColumnType("int")
                        .HasColumnName("nPeriodo");

                    b.Property<decimal>("NPrestamo")
                        .HasColumnType("money")
                        .HasColumnName("nPrestamo");

                    b.Property<int>("NProd")
                        .HasColumnType("int")
                        .HasColumnName("nProd");

                    b.Property<decimal>("NSaldoK")
                        .HasColumnType("money")
                        .HasColumnName("nSaldoK");

                    b.Property<int>("NSubProd")
                        .HasColumnType("int")
                        .HasColumnName("nSubProd");

                    b.Property<decimal?>("NTasaComision")
                        .HasColumnType("money")
                        .HasColumnName("nTasaComision");

                    b.Property<decimal?>("NTasaComp")
                        .HasColumnType("money")
                        .HasColumnName("nTasaComp");

                    b.Property<decimal?>("NTasaMor")
                        .HasColumnType("money")
                        .HasColumnName("nTasaMor");

                    b.HasKey("NCodCred")
                        .HasName("PK_Creditos_1_Tmp");

                    b.ToTable("Creditos");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamento"));

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("cNombre");

                    b.HasKey("IdDepartamento")
                        .HasName("PK__Departam__787A433DF74032C7");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Documentacion", b =>
                {
                    b.Property<int>("IdDocumentacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumentacion"));

                    b.HasKey("IdDocumentacion");

                    b.ToTable("Documentacion", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Fiador", b =>
                {
                    b.Property<int>("IdFiador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFiador"));

                    b.Property<string>("CCelular")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cCelular");

                    b.Property<string>("CDireccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cDireccion");

                    b.Property<string>("CDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cDocumento");

                    b.Property<string>("CNombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cNombres");

                    b.Property<string>("CPrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cPrimerApellido");

                    b.Property<string>("CSegundoApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cSegundoApellido");

                    b.Property<string>("CTelefono")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cTelefono");

                    b.Property<int>("NTipoDocumento")
                        .HasColumnType("int")
                        .HasColumnName("nTipoDocumento");

                    b.HasKey("IdFiador");

                    b.ToTable("Fiador", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.FotoDocumentacion", b =>
                {
                    b.Property<int>("IdFoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFoto"));

                    b.Property<int>("IdDocumentacion")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoDocumentacion")
                        .HasColumnType("int");

                    b.Property<string>("VFoto")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("vFoto");

                    b.HasKey("IdFoto")
                        .HasName("PK_FotoDocumentacion_1");

                    b.ToTable("FotoDocumentacion", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.FotoId", b =>
                {
                    b.Property<int>("IdFoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFoto"));

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<int>("NTipoFoto")
                        .HasColumnType("int")
                        .HasColumnName("nTipoFoto");

                    b.Property<string>("VFoto")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("vFoto");

                    b.HasKey("IdFoto")
                        .HasName("PK_Foto");

                    b.ToTable("FotoID", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.FotoNegocio", b =>
                {
                    b.Property<int>("IdFoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFoto"));

                    b.Property<int>("IdNegocio")
                        .HasColumnType("int");

                    b.Property<int>("NTipoFoto")
                        .HasColumnType("int")
                        .HasColumnName("nTipoFoto");

                    b.Property<string>("VFoto")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("vFoto");

                    b.HasKey("IdFoto");

                    b.ToTable("FotoNegocio", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.GarantiaFoto", b =>
                {
                    b.Property<int>("IdFoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFoto"));

                    b.Property<int>("IdArticuloGarantia")
                        .HasColumnType("int");

                    b.Property<int>("IdGarantia")
                        .HasColumnType("int");

                    b.Property<decimal>("NValor")
                        .HasColumnType("money")
                        .HasColumnName("nValor");

                    b.Property<string>("VFoto")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("vFoto");

                    b.HasKey("IdFoto")
                        .HasName("PK_FotoGarantia");

                    b.ToTable("GarantiaFoto", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Garantium", b =>
                {
                    b.Property<int>("IdGarantia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGarantia"));

                    b.HasKey("IdGarantia");

                    b.ToTable("Garantia");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.LineaCatalogoAuxiliar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CDescripcion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cDescripcion");

                    b.Property<int?>("NCatalogoCodigo")
                        .HasColumnType("int")
                        .HasColumnName("nCatalogoCodigo");

                    b.Property<int?>("NProd")
                        .HasColumnType("int")
                        .HasColumnName("nProd");

                    b.Property<int?>("NSubProd")
                        .HasColumnType("int")
                        .HasColumnName("nSubProd");

                    b.HasKey("Id")
                        .HasName("PK_LineaCreditosTemp");

                    b.ToTable("LineaCatalogoAuxiliar", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.LogErrore", b =>
                {
                    b.Property<int>("IdLogError")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogError"));

                    b.Property<string>("DatosAdicionales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaError")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("IP");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoExcepcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdLogError")
                        .HasName("PK__LogError__7B1F940EA93C6869");

                    b.ToTable("LogErrores");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Municipio", b =>
                {
                    b.Property<int>("IdMunicipio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMunicipio"));

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("cNombre");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("int");

                    b.HasKey("IdMunicipio")
                        .HasName("PK__Municipi__610059786D824024");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Negocio", b =>
                {
                    b.Property<int>("IdNegocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNegocio"));

                    b.Property<string>("CDireccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cDireccion");

                    b.Property<string>("CGeolocalizacion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cGeolocalizacion");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cNombre");

                    b.Property<int>("CSector")
                        .HasColumnType("int")
                        .HasColumnName("cSector");

                    b.Property<string>("CTelefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cTelefono");

                    b.Property<TimeOnly?>("THoraCierre")
                        .HasColumnType("time")
                        .HasColumnName("tHoraCierre");

                    b.Property<TimeOnly?>("THoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("tHoraInicio");

                    b.HasKey("IdNegocio");

                    b.ToTable("Negocio", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.PasswordChangeAudit", b =>
                {
                    b.Property<int>("IdAudit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAudit"));

                    b.Property<bool?>("Bloqueado")
                        .HasColumnType("bit");

                    b.Property<bool>("Exito")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAttempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("FechaBloqueo")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdPersona")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("IntentosFallidos")
                        .HasColumnType("int");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("MotivoBloqueo")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdAudit")
                        .HasName("PK__Password__C87E13DD960906D2");

                    b.HasIndex(new[] { "FechaAttempt" }, "IX_PasswordChangeAudits_Fecha");

                    b.HasIndex(new[] { "IdUsuario" }, "IX_PasswordChangeAudits_IdUsuario");

                    b.HasIndex(new[] { "Usuario" }, "IX_PasswordChangeAudits_Usuario");

                    b.ToTable("PasswordChangeAudits");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("CCelular")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cCelular");

                    b.Property<string>("CCorreo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cCorreo");

                    b.Property<string>("CDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cDocumento");

                    b.Property<string>("CNombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cNombres");

                    b.Property<string>("CPrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cPrimerApellido");

                    b.Property<string>("CSegundoApellido")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cSegundoApellido");

                    b.Property<string>("CTelefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cTelefono");

                    b.Property<DateOnly>("DFechaExpedicion")
                        .HasColumnType("date")
                        .HasColumnName("dFechaExpedicion");

                    b.Property<DateOnly>("DFechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("dFechaNacimiento");

                    b.Property<DateOnly>("DFechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("dFechaVencimiento");

                    b.Property<int>("NDepartamentoDoc")
                        .HasColumnType("int")
                        .HasColumnName("nDepartamentoDoc");

                    b.Property<int>("NDepartamentoNacimiento")
                        .HasColumnType("int")
                        .HasColumnName("nDepartamentoNacimiento");

                    b.Property<int>("NEscolaridad")
                        .HasColumnType("int")
                        .HasColumnName("nEscolaridad");

                    b.Property<int>("NEstadoCivil")
                        .HasColumnType("int")
                        .HasColumnName("nEstadoCivil");

                    b.Property<int>("NMunicipioDoc")
                        .HasColumnType("int")
                        .HasColumnName("nMunicipioDoc");

                    b.Property<int>("NMunicipioNacimiento")
                        .HasColumnType("int")
                        .HasColumnName("nMunicipioNacimiento");

                    b.Property<int>("NNacionalidad")
                        .HasColumnType("int")
                        .HasColumnName("nNacionalidad");

                    b.Property<int>("NProfesion")
                        .HasColumnType("int")
                        .HasColumnName("nProfesion");

                    b.Property<int>("NSexo")
                        .HasColumnType("int")
                        .HasColumnName("nSexo");

                    b.Property<int>("NTipoDocumento")
                        .HasColumnType("int")
                        .HasColumnName("nTipoDocumento");

                    b.HasKey("IdPersona");

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdRol")
                        .HasName("PK__Roles__2A49584C591AAB31");

                    b.HasIndex(new[] { "Nombre" }, "UQ__Roles__75E3EFCF90476A50")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.SalarioMinimoVigente", b =>
                {
                    b.Property<int>("NCodSalMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nCodSalMin");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NCodSalMin"));

                    b.Property<bool>("BEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("bEstado");

                    b.Property<string>("CSector")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Comercio y Servicios")
                        .HasColumnName("cSector");

                    b.Property<DateOnly?>("DFecFin")
                        .HasColumnType("date")
                        .HasColumnName("dFecFin");

                    b.Property<DateOnly>("DFecInicio")
                        .HasColumnType("date")
                        .HasColumnName("dFecInicio");

                    b.Property<decimal>("NMontoMensual")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("nMontoMensual");

                    b.HasKey("NCodSalMin")
                        .HasName("PK__SalarioM__24E830BDC3C7C532");

                    b.ToTable("SalarioMinimoVigente", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.TasaMaximaBcr", b =>
                {
                    b.Property<int>("NCodTasaMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nCodTasaMax");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NCodTasaMax"));

                    b.Property<bool>("BEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("bEstado");

                    b.Property<DateOnly>("DFecFin")
                        .HasColumnType("date")
                        .HasColumnName("dFecFin");

                    b.Property<DateOnly>("DFecInicio")
                        .HasColumnType("date")
                        .HasColumnName("dFecInicio");

                    b.Property<DateOnly>("DFecPublicacion")
                        .HasColumnType("date")
                        .HasColumnName("dFecPublicacion");

                    b.Property<int>("NCodSegmento")
                        .HasColumnType("int")
                        .HasColumnName("nCodSegmento");

                    b.Property<decimal>("NTasaMaxima")
                        .HasColumnType("decimal(7, 4)")
                        .HasColumnName("nTasaMaxima");

                    b.HasKey("NCodTasaMax")
                        .HasName("PK__TasaMaxi__650D6D6E667849EF");

                    b.HasIndex("NCodSegmento");

                    b.ToTable("TasaMaximaBCR", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.UsuarioLogin", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool?>("BContrasenaTemporal")
                        .HasColumnType("bit")
                        .HasColumnName("bContrasenaTemporal");

                    b.Property<int?>("Bloqueado")
                        .HasColumnType("int");

                    b.Property<string>("CCorreo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cCorreo");

                    b.Property<string>("CDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cDocumento");

                    b.Property<DateTime?>("DFechaContrasenaTemporal")
                        .HasColumnType("datetime")
                        .HasColumnName("dFechaContrasenaTemporal");

                    b.Property<int?>("Estado")
                        .HasColumnType("int");

                    b.Property<int?>("FechaBloqueo")
                        .HasColumnType("int");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<int?>("IntentosFallidos")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("Token")
                        .HasColumnType("int");

                    b.Property<bool?>("TokenCheck")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TokenTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime");

                    b.HasKey("IdUsuario")
                        .HasName("PK_UsuaroLogin");

                    b.ToTable("UsuarioLogin", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.UsuarioRole", b =>
                {
                    b.Property<int>("IdUsuarioRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioRol"));

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuarioRol")
                        .HasName("PK__UsuarioR__6806BF4AC5289D17");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "IdUsuario", "IdRol" }, "UQ_UsuarioRoles")
                        .IsUnique();

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<string>("CProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cProducto");

                    b.Property<int>("IdNegocio")
                        .HasColumnType("int");

                    b.Property<decimal>("NCantidadVenta")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("nCantidadVenta");

                    b.Property<decimal>("NPrecioTotal")
                        .HasColumnType("money")
                        .HasColumnName("nPrecioTotal");

                    b.Property<decimal>("NPrecioXunidad")
                        .HasColumnType("money")
                        .HasColumnName("nPrecioXUnidad");

                    b.Property<int>("NUnidadMedida")
                        .HasColumnType("int")
                        .HasColumnName("nUnidadMedida");

                    b.HasKey("IdVenta");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.VerNegocio", b =>
                {
                    b.Property<int>("NCodVar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nCodVar");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NCodVar"));

                    b.Property<string>("CNomVar")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("cNomVar");

                    b.Property<string>("CValorVar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cValorVar");

                    b.Property<int>("NTipoVar")
                        .HasColumnType("int")
                        .HasColumnName("nTipoVar");

                    b.HasKey("NCodVar");

                    b.ToTable("VerNegocio", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Municipio", b =>
                {
                    b.HasOne("CrediAvanzaAPI.Models.Departamento", "IdDepartamentoNavigation")
                        .WithMany("Municipios")
                        .HasForeignKey("IdDepartamento")
                        .IsRequired()
                        .HasConstraintName("FK_Municipios_Departamentos");

                    b.Navigation("IdDepartamentoNavigation");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.TasaMaximaBcr", b =>
                {
                    b.HasOne("CrediAvanzaAPI.Models.CatSegmentoUsura", "NCodSegmentoNavigation")
                        .WithMany("TasaMaximaBcrs")
                        .HasForeignKey("NCodSegmento")
                        .IsRequired()
                        .HasConstraintName("FK__TasaMaxim__nCodS__57A801BA");

                    b.Navigation("NCodSegmentoNavigation");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.UsuarioRole", b =>
                {
                    b.HasOne("CrediAvanzaAPI.Models.Role", "IdRolNavigation")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioRoles_Roles");

                    b.HasOne("CrediAvanzaAPI.Models.UsuarioLogin", "IdUsuarioNavigation")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioRoles_Usuario");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CatSegmentoUsura", b =>
                {
                    b.Navigation("TasaMaximaBcrs");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Departamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Role", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.UsuarioLogin", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
