// <auto-generated />
using System;
using CrediAvanzaAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrediAvanzaAPI.Migrations
{
    [DbContext(typeof(DbNegocioContext))]
    [Migration("20260324223508_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CrediAvanzaAPI.Models.CatalogoCodigo", b =>
                {
                    b.Property<int>("NCodigo")
                        .HasColumnType("int")
                        .HasColumnName("nCodigo");

                    b.Property<int>("NValor")
                        .HasColumnType("int")
                        .HasColumnName("nValor");

                    b.Property<string>("CNomCod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cNomCod");

                    b.Property<int?>("NEstados")
                        .HasColumnType("int")
                        .HasColumnName("nEstados");

                    b.Property<int?>("NTipoCodigo")
                        .HasColumnType("int")
                        .HasColumnName("nTipoCodigo");

                    b.HasKey("NCodigo", "NValor");

                    b.ToTable("CatalogoCodigos");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<string>("CProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cProducto");

                    b.Property<int>("IdNegocio")
                        .HasColumnType("int");

                    b.Property<int>("NCantidadCompra")
                        .HasColumnType("int")
                        .HasColumnName("nCantidadCompra");

                    b.Property<decimal>("NPrecioTotal")
                        .HasColumnType("money")
                        .HasColumnName("nPrecioTotal");

                    b.Property<decimal>("NPrecioXunidad")
                        .HasColumnType("money")
                        .HasColumnName("nPrecioXUnidad");

                    b.Property<int>("NUnidadMedida")
                        .HasColumnType("int")
                        .HasColumnName("nUnidadMedida");

                    b.HasKey("IdCompra")
                        .HasName("PK_CompraDetalle");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Conyuge", b =>
                {
                    b.Property<int>("IdConyuge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConyuge"));

                    b.Property<string>("CCelular")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cCelular");

                    b.Property<string>("CDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cDocumento");

                    b.Property<string>("CNombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cNombres");

                    b.Property<string>("CPrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cPrimerApellido");

                    b.Property<string>("CSegundoApellido")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cSegundoApellido");

                    b.Property<string>("CTelefono")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cTelefono");

                    b.Property<int>("NTipoDocumento")
                        .HasColumnType("int")
                        .HasColumnName("nTipoDocumento");

                    b.HasKey("IdConyuge");

                    b.ToTable("Conyuge", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CredCalenGasto", b =>
                {
                    b.Property<int>("IdCalenGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCalenGasto"));

                    b.Property<DateTime>("DFecAsig")
                        .HasColumnType("datetime")
                        .HasColumnName("dFecAsig");

                    b.Property<int?>("NCodAgePersAsig")
                        .HasColumnType("int")
                        .HasColumnName("nCodAgePersAsig");

                    b.Property<int>("NCodGasto")
                        .HasColumnType("int")
                        .HasColumnName("nCodGasto");

                    b.Property<decimal>("NMonto")
                        .HasColumnType("money")
                        .HasColumnName("nMonto");

                    b.Property<decimal?>("NMontoIgv")
                        .HasColumnType("money")
                        .HasColumnName("nMontoIGV");

                    b.Property<decimal?>("NMontoIgvpag")
                        .HasColumnType("money")
                        .HasColumnName("nMontoIGVPag");

                    b.Property<decimal>("NMontoPag")
                        .HasColumnType("money")
                        .HasColumnName("nMontoPag");

                    b.Property<decimal?>("NMontoSinIgv")
                        .HasColumnType("money")
                        .HasColumnName("nMontoSinIGV");

                    b.Property<decimal?>("NMontoSinIgvpag")
                        .HasColumnType("money")
                        .HasColumnName("nMontoSinIGVPag");

                    b.Property<int>("NNroCalen")
                        .HasColumnType("int")
                        .HasColumnName("nNroCalen");

                    b.Property<int>("NNroCuota")
                        .HasColumnType("int")
                        .HasColumnName("nNroCuota");

                    b.HasKey("IdCalenGasto");

                    b.ToTable("CredCalenGastos");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CredCalendCond", b =>
                {
                    b.Property<int>("IdCredCalendCond")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCredCalendCond"));

                    b.Property<bool?>("BCobroDom")
                        .HasColumnType("bit")
                        .HasColumnName("bCobroDom");

                    b.Property<bool?>("BCobroFer")
                        .HasColumnType("bit")
                        .HasColumnName("bCobroFer");

                    b.Property<bool?>("BCobroSab")
                        .HasColumnType("bit")
                        .HasColumnName("bCobroSab");

                    b.Property<bool?>("BCuotaDoble")
                        .HasColumnType("bit")
                        .HasColumnName("bCuotaDoble");

                    b.Property<int?>("IdCalenGasto")
                        .HasColumnType("int");

                    b.Property<int?>("IdCalendario")
                        .HasColumnType("int");

                    b.Property<int?>("NCodLineaSecundario")
                        .HasColumnType("int")
                        .HasColumnName("nCodLineaSecundario");

                    b.Property<int>("NCuotas")
                        .HasColumnType("int")
                        .HasColumnName("nCuotas");

                    b.Property<int?>("NDiaFijo")
                        .HasColumnType("int")
                        .HasColumnName("nDiaFijo");

                    b.Property<decimal>("NGasto")
                        .HasColumnType("money")
                        .HasColumnName("nGasto");

                    b.Property<int>("NNroCalen")
                        .HasColumnType("int")
                        .HasColumnName("nNroCalen");

                    b.Property<int>("NPlazo")
                        .HasColumnType("int")
                        .HasColumnName("nPlazo");

                    b.Property<int?>("NTipoCargo")
                        .HasColumnType("int")
                        .HasColumnName("nTipoCargo");

                    b.HasKey("IdCredCalendCond");

                    b.ToTable("CredCalendCond", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CredCalendario", b =>
                {
                    b.Property<int>("IdCalendario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCalendario"));

                    b.Property<DateTime?>("DFecPago")
                        .HasColumnType("datetime")
                        .HasColumnName("dFecPago");

                    b.Property<DateTime>("DFecVenc")
                        .HasColumnType("datetime")
                        .HasColumnName("dFecVenc");

                    b.Property<DateTime?>("DFecpro")
                        .HasColumnType("datetime")
                        .HasColumnName("dFecpro");

                    b.Property<decimal>("NCapPag")
                        .HasColumnType("money")
                        .HasColumnName("nCapPag");

                    b.Property<decimal>("NCapital")
                        .HasColumnType("money")
                        .HasColumnName("nCapital");

                    b.Property<int>("NEstado")
                        .HasColumnType("int")
                        .HasColumnName("nEstado");

                    b.Property<decimal>("NIgv")
                        .HasColumnType("money")
                        .HasColumnName("nIgv");

                    b.Property<decimal>("NIgvPag")
                        .HasColumnType("money")
                        .HasColumnName("nIgvPag");

                    b.Property<decimal>("NIntComp")
                        .HasColumnType("money")
                        .HasColumnName("nIntComp");

                    b.Property<decimal>("NIntMor")
                        .HasColumnType("money")
                        .HasColumnName("nIntMor");

                    b.Property<decimal>("NIntMorPag")
                        .HasColumnType("money")
                        .HasColumnName("nIntMorPag");

                    b.Property<decimal>("NIntPag")
                        .HasColumnType("money")
                        .HasColumnName("nIntPag");

                    b.Property<int>("NNroCalen")
                        .HasColumnType("int")
                        .HasColumnName("nNroCalen");

                    b.Property<int>("NNroCuota")
                        .HasColumnType("int")
                        .HasColumnName("nNroCuota");

                    b.Property<int?>("NTipoCargo")
                        .HasColumnType("int")
                        .HasColumnName("nTipoCargo");

                    b.HasKey("IdCalendario")
                        .HasName("PK_CredCalendario_1");

                    b.ToTable("CredCalendario", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CredCambioGasto", b =>
                {
                    b.Property<int>("NIdCambio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nIdCambio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NIdCambio"));

                    b.Property<DateOnly>("DFechaCambio")
                        .HasColumnType("date")
                        .HasColumnName("dFechaCambio");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("NCodCred")
                        .HasColumnType("int")
                        .HasColumnName("nCodCred");

                    b.Property<decimal>("NMontoNuevo")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("nMontoNuevo");

                    b.Property<decimal>("NMontoOriginal")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("nMontoOriginal");

                    b.HasKey("NIdCambio");

                    b.ToTable("CredCambioGasto", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CredFeriado", b =>
                {
                    b.Property<int>("NIdFeriado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nIdFeriado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NIdFeriado"));

                    b.Property<bool>("BEstado")
                        .HasColumnType("bit")
                        .HasColumnName("bEstado");

                    b.Property<string>("CDescripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("cDescripcion");

                    b.Property<DateTime>("DFecha")
                        .HasColumnType("datetime")
                        .HasColumnName("dFecha");

                    b.HasKey("NIdFeriado");

                    b.ToTable("CredFeriado", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CredFeriadoAge", b =>
                {
                    b.Property<int>("IdCredFeriadoAge")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCredFeriadoAge"));

                    b.Property<DateTime>("DFecha")
                        .HasColumnType("datetime")
                        .HasColumnName("dFecha");

                    b.Property<int>("NCodAge")
                        .HasColumnType("int")
                        .HasColumnName("nCodAge");

                    b.Property<int>("NIdFeriado")
                        .HasColumnType("int")
                        .HasColumnName("nIdFeriado");

                    b.HasKey("IdCredFeriadoAge");

                    b.ToTable("CredFeriadoAge", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.CredGasto", b =>
                {
                    b.Property<int>("IdGasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGasto"));

                    b.Property<string>("CDescripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cDescripcion");

                    b.Property<int>("NPeriodo")
                        .HasColumnType("int")
                        .HasColumnName("nPeriodo");

                    b.Property<int>("NProd")
                        .HasColumnType("int")
                        .HasColumnName("nProd");

                    b.Property<decimal>("NRangoFinal")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("nRangoFinal");

                    b.Property<decimal>("NRangoInicial")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("nRangoInicial");

                    b.Property<int>("NSubProd")
                        .HasColumnType("int")
                        .HasColumnName("nSubProd");

                    b.Property<int>("NTipoCargo")
                        .HasColumnType("int")
                        .HasColumnName("nTipoCargo");

                    b.Property<int>("NTipoGasto")
                        .HasColumnType("int")
                        .HasColumnName("nTipoGasto");

                    b.Property<decimal>("NValor")
                        .HasColumnType("money")
                        .HasColumnName("nValor");

                    b.HasKey("IdGasto");

                    b.ToTable("CredGastos");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Credito", b =>
                {
                    b.Property<int>("NCodCred")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nCodCred");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NCodCred"));

                    b.Property<DateTime>("DFecVig")
                        .HasColumnType("datetime")
                        .HasColumnName("dFecVig");

                    b.Property<int?>("IdCalendario")
                        .HasColumnType("int");

                    b.Property<int?>("IdConyuge")
                        .HasColumnType("int");

                    b.Property<int?>("IdCredCalendCond")
                        .HasColumnType("int");

                    b.Property<int?>("IdDocumentacion")
                        .HasColumnType("int");

                    b.Property<int?>("IdFiador")
                        .HasColumnType("int");

                    b.Property<int?>("IdGarantia")
                        .HasColumnType("int");

                    b.Property<int?>("IdNegocio")
                        .HasColumnType("int");

                    b.Property<int?>("IdPersona")
                        .HasColumnType("int");

                    b.Property<int?>("NAceptaTerminos")
                        .HasColumnType("int")
                        .HasColumnName("nAceptaTerminos");

                    b.Property<int?>("NCiclo")
                        .HasColumnType("int")
                        .HasColumnName("nCiclo");

                    b.Property<int?>("NCobroEnAgencia")
                        .HasColumnType("int")
                        .HasColumnName("nCobroEnAgencia");

                    b.Property<int>("NCodAge")
                        .HasColumnType("int")
                        .HasColumnName("nCodAge");

                    b.Property<int?>("NCodLinea")
                        .HasColumnType("int")
                        .HasColumnName("nCodLinea");

                    b.Property<int?>("NDiasAtraso")
                        .HasColumnType("int")
                        .HasColumnName("nDiasAtraso");

                    b.Property<int>("NEstado")
                        .HasColumnType("int")
                        .HasColumnName("nEstado");

                    b.Property<decimal?>("NMontoCuota")
                        .HasColumnType("money")
                        .HasColumnName("nMontoCuota");

                    b.Property<decimal?>("NMora")
                        .HasColumnType("money")
                        .HasColumnName("nMora");

                    b.Property<int>("NNroCuotas")
                        .HasColumnType("int")
                        .HasColumnName("nNroCuotas");

                    b.Property<int>("NNroProxCuota")
                        .HasColumnType("int")
                        .HasColumnName("nNroProxCuota");

                    b.Property<int>("NPeriodo")
                        .HasColumnType("int")
                        .HasColumnName("nPeriodo");

                    b.Property<decimal>("NPrestamo")
                        .HasColumnType("money")
                        .HasColumnName("nPrestamo");

                    b.Property<int>("NProd")
                        .HasColumnType("int")
                        .HasColumnName("nProd");

                    b.Property<decimal>("NSaldoK")
                        .HasColumnType("money")
                        .HasColumnName("nSaldoK");

                    b.Property<int>("NSubProd")
                        .HasColumnType("int")
                        .HasColumnName("nSubProd");

                    b.Property<decimal?>("NTasaComision")
                        .HasColumnType("money")
                        .HasColumnName("nTasaComision");

                    b.Property<decimal?>("NTasaComp")
                        .HasColumnType("money")
                        .HasColumnName("nTasaComp");

                    b.Property<decimal?>("NTasaMor")
                        .HasColumnType("money")
                        .HasColumnName("nTasaMor");

                    b.HasKey("NCodCred")
                        .HasName("PK_Creditos_1");

                    b.ToTable("Creditos");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Documentacion", b =>
                {
                    b.Property<int>("IdDocumentacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumentacion"));

                    b.HasKey("IdDocumentacion");

                    b.ToTable("Documentacion", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Fiador", b =>
                {
                    b.Property<int>("IdFiador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFiador"));

                    b.Property<string>("CCelular")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cCelular");

                    b.Property<string>("CDireccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cDireccion");

                    b.Property<string>("CDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cDocumento");

                    b.Property<string>("CNombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cNombres");

                    b.Property<string>("CPrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cPrimerApellido");

                    b.Property<string>("CSegundoApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cSegundoApellido");

                    b.Property<string>("CTelefono")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cTelefono");

                    b.Property<int>("NTipoDocumento")
                        .HasColumnType("int")
                        .HasColumnName("nTipoDocumento");

                    b.HasKey("IdFiador");

                    b.ToTable("Fiador", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.FotoDocumentacion", b =>
                {
                    b.Property<int>("IdFoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFoto"));

                    b.Property<int>("IdDocumentacion")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoDocumentacion")
                        .HasColumnType("int");

                    b.Property<string>("VFoto")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("vFoto");

                    b.HasKey("IdFoto")
                        .HasName("PK_FotoDocumentacion_1");

                    b.ToTable("FotoDocumentacion", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.FotoId", b =>
                {
                    b.Property<int>("IdFoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFoto"));

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<int>("NTipoFoto")
                        .HasColumnType("int")
                        .HasColumnName("nTipoFoto");

                    b.Property<string>("VFoto")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("vFoto");

                    b.HasKey("IdFoto")
                        .HasName("PK_Foto");

                    b.ToTable("FotoID", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.FotoNegocio", b =>
                {
                    b.Property<int>("IdFoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFoto"));

                    b.Property<int>("IdNegocio")
                        .HasColumnType("int");

                    b.Property<int>("NTipoFoto")
                        .HasColumnType("int")
                        .HasColumnName("nTipoFoto");

                    b.Property<string>("VFoto")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("vFoto");

                    b.HasKey("IdFoto");

                    b.ToTable("FotoNegocio", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Garantium", b =>
                {
                    b.Property<int>("IdGarantia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGarantia"));

                    b.Property<int>("NIdArticuloGarantia")
                        .HasColumnType("int")
                        .HasColumnName("nIdArticuloGarantia");

                    b.Property<int>("NIdFotoGarantia")
                        .HasColumnType("int")
                        .HasColumnName("nIdFotoGarantia");

                    b.Property<decimal>("NValor")
                        .HasColumnType("money")
                        .HasColumnName("nValor");

                    b.HasKey("IdGarantia");

                    b.ToTable("Garantia");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.LogErrore", b =>
                {
                    b.Property<int>("IdLogError")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogError"));

                    b.Property<string>("DatosAdicionales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaError")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("IP");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoExcepcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdLogError")
                        .HasName("PK__LogError__7B1F940EA93C6869");

                    b.ToTable("LogErrores");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Negocio", b =>
                {
                    b.Property<int>("IdNegocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNegocio"));

                    b.Property<string>("CDireccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cDireccion");

                    b.Property<string>("CGeolocalizacion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cGeolocalizacion");

                    b.Property<string>("CNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cNombre");

                    b.Property<int>("CSector")
                        .HasColumnType("int")
                        .HasColumnName("cSector");

                    b.Property<string>("CTelefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cTelefono");

                    b.Property<TimeOnly?>("THoraCierre")
                        .HasColumnType("time")
                        .HasColumnName("tHoraCierre");

                    b.Property<TimeOnly?>("THoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("tHoraInicio");

                    b.HasKey("IdNegocio");

                    b.ToTable("Negocio", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("CCorreo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cCorreo");

                    b.Property<string>("CDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cDocumento");

                    b.Property<string>("CNombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cNombres");

                    b.Property<string>("CPrimerApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cPrimerApellido");

                    b.Property<string>("CSegundoApellido")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cSegundoApellido");

                    b.Property<DateOnly>("DFechaExpedicion")
                        .HasColumnType("date")
                        .HasColumnName("dFechaExpedicion");

                    b.Property<DateOnly>("DFechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("dFechaNacimiento");

                    b.Property<DateOnly>("DFechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("dFechaVencimiento");

                    b.Property<int>("NDepartamentoDoc")
                        .HasColumnType("int")
                        .HasColumnName("nDepartamentoDoc");

                    b.Property<int>("NDepartamentoNacimiento")
                        .HasColumnType("int")
                        .HasColumnName("nDepartamentoNacimiento");

                    b.Property<int>("NEscolaridad")
                        .HasColumnType("int")
                        .HasColumnName("nEscolaridad");

                    b.Property<int>("NEstadoCivil")
                        .HasColumnType("int")
                        .HasColumnName("nEstadoCivil");

                    b.Property<int>("NMunicipioDoc")
                        .HasColumnType("int")
                        .HasColumnName("nMunicipioDoc");

                    b.Property<int>("NMunicipioNacimiento")
                        .HasColumnType("int")
                        .HasColumnName("nMunicipioNacimiento");

                    b.Property<int>("NNacionalidad")
                        .HasColumnType("int")
                        .HasColumnName("nNacionalidad");

                    b.Property<int>("NProfesion")
                        .HasColumnType("int")
                        .HasColumnName("nProfesion");

                    b.Property<int>("NSexo")
                        .HasColumnType("int")
                        .HasColumnName("nSexo");

                    b.Property<int>("NTipoDocumento")
                        .HasColumnType("int")
                        .HasColumnName("nTipoDocumento");

                    b.HasKey("IdPersona");

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<string>("CProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cProducto");

                    b.Property<int>("IdNegocio")
                        .HasColumnType("int");

                    b.Property<int>("NCantidadVenta")
                        .HasColumnType("int")
                        .HasColumnName("nCantidadVenta");

                    b.Property<decimal>("NPrecioTotal")
                        .HasColumnType("money")
                        .HasColumnName("nPrecioTotal");

                    b.Property<decimal>("NPrecioXunidad")
                        .HasColumnType("money")
                        .HasColumnName("nPrecioXUnidad");

                    b.Property<int>("NUnidadMedida")
                        .HasColumnType("int")
                        .HasColumnName("nUnidadMedida");

                    b.HasKey("IdVenta");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("CrediAvanzaAPI.Models.VerNegocio", b =>
                {
                    b.Property<int>("NCodVar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("nCodVar");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NCodVar"));

                    b.Property<string>("CNomVar")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("cNomVar");

                    b.Property<string>("CValorVar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("cValorVar");

                    b.Property<int>("NTipoVar")
                        .HasColumnType("int")
                        .HasColumnName("nTipoVar");

                    b.HasKey("NCodVar");

                    b.ToTable("VerNegocio", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
